# PostgreSQL 接続設定  補足としてDetaBese名はattandance��やること!!無い場合は作成する事!!

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=kuroshima
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.platform=postgresql
spring.datasource.initialization-mode=always
spring.resources.static-locations=classpath:/static/
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.entity_manager_factory_interface=jakarta.persistence.EntityManagerFactory
spring.devtools.enabled=false

